<?=$this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('ZF2 '. $this->translate('Shop Online'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
        <!-- Le styles -->
        <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/jquery.pslider.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ; ?>
        <?=$this->headScript()
            ->prependFile($this->basePath('js/jquery.pslider.js'))
            ->prependFile($this->basePath('js/jquery.lazyload.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>
    </head>
    <body>
        <?=$this->partial('layout/header'); ?>
        <?=$this->partial('layout/contentMenu'); ?>
        <?=$this->content?>
        <?=$this->partial('layout/footer'); ?>
        <!-- Scripts -->
        <?=$this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/quyen.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </body>
</html>
