<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from thevectorlab.net/flatlab/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 14 Aug 2015 03:43:56 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?=$this->headTitle( $this->translate('Login Control Panel'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('assets/css/bootstrap.css'))
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('assets/css/style-responsive.css'))
        ->prependStylesheet($this->basePath('assets/css/font-awesome.min.css'))
    ; ?>
</head>

  <body class="login-body">
    <div class="container">
    <form method="post" name="loginForm" action="login" class="form-signin" id="loginForm">      
      <h2 class="form-signin-heading">Đăng nhập hệ thống</h2>
      <?php if(isset($message)){ ?><div style="color: red; text-align:center;border-radius: 0; padding: 10px; text-transform: none"><?=$message?></div><?php } ?>
      <div class="login-wrap">
        <input type="text" name="username" class="form-control" placeholder="Username" value="">
        <input type="password" name="password" class="form-control" placeholder="Password" value="">
        <input type="submit" name="submit" id="submit" class="btn btn-lg btn-login btn-block" value="Đăng nhập">      
      <div>
      <h5 class="text-right">
        <a data-toggle="modal" href="#myModal"> Quên mật khẩu?</a>
      </h5>
    </form>
    </div>
  </body>
  <?=$this->headScript()
      ->prependFile($this->basePath('assets/js/jquery.min.js'))
  ; ?>
<script type="text/javascript">
  $('.form-signin').on('submit', function(event){
    var input = $('.form-signin input');
    $(input).each(function(){
      if($(this).val() === '')
      {
        alert('Vui lòng điền đầy đủ Username và Password!');
        event.preventDefault();
        return false;
      }
    })
  })
</script>
</html>
